                                                                                                                                                              ERROR:daisy.client:Block downscale/801 with read ROI [3200:6400, 3584:3840, 0:256] (3200, 256, 256) and write ROI [3200:6400, 3584:3840, 0:256] (3200, 256, 256) failed in worker 483
Traceback (most recent call last):
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/client.py", line 85, in acquire_block
    yield block
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/task.py", line 179, in _process_blocks
    self.process_function(block)
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 688, in <lambda>
    process_function=lambda b: downscale_block(
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 640, in downscale_block
    out_data = skimage.measure.block_reduce(in_data, factor, np.mean)
NameError: name 'skimage' is not defined
downscale ▶:   0%|                                                                                  | 0/7056 [00:13<?, ?blocks/s, ⧗=0, ▶=53, ✔=0, ✗=2229, ∅=0]                                                                                                                                                              ERROR:daisy.client:Block downscale/5593 with read ROI [3200:6400, 3840:4096, 3840:4096] (3200, 256, 256) and write ROI [3200:6400, 3840:4096, 3840:4096] (3200, 256, 256) failed in worker 483
Traceback (most recent call last):
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/client.py", line 85, in acquire_block
    yield block
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/task.py", line 179, in _process_blocks
    self.process_function(block)
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 688, in <lambda>
    process_function=lambda b: downscale_block(
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 640, in downscale_block
    out_data = skimage.measure.block_reduce(in_data, factor, np.mean)
NameError: name 'skimage' is not defined
downscale ▶:   0%|                                                                                  | 0/7056 [00:13<?, ?blocks/s, ⧗=0, ▶=53, ✔=0, ✗=2229, ∅=0]                                                                                                                                                              ERROR:daisy.client:Block downscale/17450 with read ROI [3200:6400, 4096:4352, 7424:7680] (3200, 256, 256) and write ROI [3200:6400, 4096:4352, 7424:7680] (3200, 256, 256) failed in worker 483
Traceback (most recent call last):
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/client.py", line 85, in acquire_block
    yield block
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/task.py", line 179, in _process_blocks
    self.process_function(block)
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 688, in <lambda>
    process_function=lambda b: downscale_block(
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 640, in downscale_block
    out_data = skimage.measure.block_reduce(in_data, factor, np.mean)
NameError: name 'skimage' is not defined
downscale ▶:   0%|                                                                                  | 0/7056 [00:13<?, ?blocks/s, ⧗=0, ▶=53, ✔=0, ✗=2229, ∅=0]                                                                                                                                                              ERROR:daisy.client:Block downscale/2215 with read ROI [3200:6400, 4608:4864, 768:1024] (3200, 256, 256) and write ROI [3200:6400, 4608:4864, 768:1024] (3200, 256, 256) failed in worker 483
Traceback (most recent call last):
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/client.py", line 85, in acquire_block
    yield block
  File "/Users/joelyancey/.local/share/virtualenvs/swift-ir-AuCIf4YN/lib/python3.9/site-packages/daisy/task.py", line 179, in _process_blocks
    self.process_function(block)
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 688, in <lambda>
    process_function=lambda b: downscale_block(
  File "/Users/joelyancey/glanceem_swift/swift-ir/alignEM/package/scale_pyramid.py", line 640, in downscale_block
    out_data = skimage.measure.block_reduce(in_data, factor, np.mean)
NameError: name 'skimage' is not defined
downscale ▶:   0%|                                                                                  | 0/7056 [00:14<?, ?blocks/s, ⧗=0, ▶=53, ✔=0, ✗=2229, ∅=0]